[package]
name = "vmp-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "vmp"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
getrandom.workspace = true
serde.workspace = true
serde_json.workspace = true
vmp-compiler = { version = "0.1.0", path = "../vmp-compiler" }
vmp-ir = { version = "0.1.0", path = "../vmp-ir" }
vmp-pe = { version = "0.1.0", path = "../vmp-pe" }
vmp-types = { version = "0.1.0", path = "../vmp-types" }
vmp-x86 = { version = "0.1.0", path = "../vmp-x86" }

[dev-dependencies]
iced-x86.workspace = true

[lints]
workspace = true
