"""Observe every generated byte decrypt/key transition before dispatch or operand use."""
import json
import hashlib
import subprocess
import sys
import unittest
from pathlib import Path

from body_instance import ROOT, CASES, execute


class EncryptedBodyTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        output = subprocess.check_output([
            'cargo', 'run', '--quiet', '-p', 'vmp-vm', '--no-default-features',
            '--example', 'body_instance', '--', '--encrypted'], cwd=ROOT, text=True)
        cls.artifacts = [json.loads(line) for line in output.splitlines()]
        assert [a['variant'] for a in cls.artifacts] == list(range(256))

    def test_every_field_and_seven_results_across_all_layouts(self):
        for artifact in self.artifacts:
            for case in CASES:
                with self.subTest(variant=artifact['variant'], case=case):
                    fields = execute(artifact, case)
                    self.assertEqual(len(fields), 13)

    def test_ciphertext_corruption(self):
        with self.assertRaisesRegex(AssertionError, 'decrypted field'):
            execute(self.artifacts[0], CASES[1], 'ciphertext')

    def test_initial_key_corruption(self):
        with self.assertRaisesRegex(AssertionError, 'decrypted field'):
            execute(self.artifacts[0], CASES[1], 'initial-key')

    def test_native_decryptor_corruption(self):
        with self.assertRaisesRegex(AssertionError, 'decrypted field'):
            execute(self.artifacts[0], CASES[1], 'decryptor')


if __name__ == '__main__':
    if len(sys.argv) == 3 and sys.argv[1] == '--export':
        EncryptedBodyTests.setUpClass()
        artifacts = EncryptedBodyTests.artifacts
        with Path(sys.argv[2]).open('w') as output:
            for artifact in artifacts:
                fields = execute(artifact, CASES[1])
                output.write(json.dumps(dict(artifact=artifact, case=CASES[1], fields=fields,
                    image_sha256=hashlib.sha256(bytes(artifact['image'])).hexdigest())) + '\n')
        print(f'Exported {len(artifacts)} instances, {len(artifacts) * 13} field transitions')
    else:
        unittest.main()
