[package]
name = "vmp-runtime-windows"
version = "0.1.0"
edition = "2021"

[features]
windows-runtime-probe = []

[dependencies]
iced-x86.workspace = true
thiserror.workspace = true
vmp-types = { version = "0.1.0", path = "../vmp-types" }
vmp-vm = { version = "0.1.0", path = "../vmp-vm" }

[dev-dependencies]
vmp-pe = { version = "0.1.0", path = "../vmp-pe" }

[target.'cfg(all(windows, target_arch = "x86_64"))'.dev-dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_System_Diagnostics_Debug", "Win32_System_Kernel", "Win32_System_Memory", "Win32_System_Threading"] }

[lints]
workspace = true

[[test]]
name = "windows_runtime"
path = "tests/windows_runtime.rs"
required-features = ["windows-runtime-probe"]
