//! OS calls and an external Windows-ABI register snapshot wrapper for owned test code
#![allow(unsafe_code)]

use iced_x86::code_asm::*;
use std::ffi::c_void;
use std::os::windows::ffi::OsStrExt;
use std::path::Path;
use vmp_types::Rva;

#[link(name = "kernel32")]
extern "system" {
    fn LoadLibraryW(path: *const u16) -> *mut c_void;
    fn FreeLibrary(module: *mut c_void) -> i32;
    fn VirtualAlloc(
        address: *mut c_void,
        size: usize,
        allocation: u32,
        protection: u32,
    ) -> *mut c_void;
    fn VirtualFree(address: *mut c_void, size: usize, kind: u32) -> i32;
    fn VirtualProtect(address: *mut c_void, size: usize, protection: u32, old: *mut u32) -> i32;
    fn FlushInstructionCache(process: *mut c_void, address: *const c_void, size: usize) -> i32;
    fn GetCurrentProcess() -> *mut c_void;
    fn GetLastError() -> u32;
}

pub struct Reservation(*mut c_void);
impl Reservation {
    pub fn at(base: u64) -> Self {
        // SAFETY: Reserves an uncommitted page at the fixture's preferred base without overwriting memory
        let address = unsafe { VirtualAlloc(base as *mut c_void, 4096, 0x2000, 1) };
        if address.is_null() {
            // SAFETY: Reads this thread's error immediately after VirtualAlloc
            assert_eq!(
                unsafe { GetLastError() },
                487,
                "preferred base must be occupied or reserved"
            );
        } else {
            assert_eq!(address as u64, base);
        }
        Self(address)
    }
}
impl Drop for Reservation {
    fn drop(&mut self) {
        if !self.0.is_null() {
            // SAFETY: Releases only the reservation owned by this object
            assert_ne!(unsafe { VirtualFree(self.0, 0, 0x8000) }, 0);
        }
    }
}

pub struct Module {
    handle: *mut c_void,
    size: usize,
}
impl Module {
    pub fn load(path: &Path, size: usize) -> Self {
        let wide: Vec<_> = path.as_os_str().encode_wide().chain(Some(0)).collect();
        // SAFETY: NUL-terminated absolute path to the owned test DLL, alive for the call
        let handle = unsafe { LoadLibraryW(wide.as_ptr()) };
        assert!(
            !handle.is_null(),
            "LoadLibraryW: {}",
            std::io::Error::last_os_error()
        );
        Self { handle, size }
    }

    pub fn base(&self) -> u64 {
        self.handle as u64
    }

    pub fn qword(&self, rva: Rva) -> u64 {
        let offset = rva.get() as usize;
        assert!(offset.checked_add(8).is_some_and(|end| end <= self.size));
        // SAFETY: The parsed fixture fixup lies in a readable section of this still-loaded DLL
        unsafe { (self.handle.cast::<u8>().add(offset).cast::<u64>()).read_unaligned() }
    }

    pub fn snapshot(&self, entry: Rva, lhs: u64, rhs: u64) -> [u64; 20] {
        assert!((entry.get() as usize) < self.size);
        const SIZE: usize = 0x10000;
        // SAFETY: Creates a fresh private RW mapping for the external snapshot wrapper
        let address = unsafe { VirtualAlloc(std::ptr::null_mut(), SIZE, 0x3000, 4) };
        assert!(!address.is_null());
        let allocation = Reservation(address);
        let mut initial = std::array::from_fn(|i| 0x1111000000000000 + i as u64);
        initial[1] = lhs;
        initial[2] = rhs;
        let code = probe(
            self.base() + u64::from(entry.get()),
            address as u64,
            &initial,
        );
        assert!(code.len() <= SIZE);
        let mut old = 0;
        // SAFETY: Fresh writable allocation is disjoint from code, and code fits entirely within it
        unsafe { std::ptr::copy_nonoverlapping(code.as_ptr(), address.cast::<u8>(), code.len()) };
        // SAFETY: Changes the owned mapping to RX before invocation, with a valid old-protection pointer
        assert_ne!(unsafe { VirtualProtect(address, SIZE, 0x20, &mut old) }, 0);
        // SAFETY: Flushes the generated bytes in the current process before executing them
        assert_ne!(
            unsafe { FlushInstructionCache(GetCurrentProcess(), address, code.len()) },
            0
        );
        let mut output = [0; 20];
        // SAFETY: Wrapper obeys the Windows x64 ABI, writes exactly 20 output qwords at most,
        // preserves nonvolatile registers, and calls only the live fixture/gate with benign flags
        unsafe {
            let call: extern "system" fn(*mut u64) = std::mem::transmute(address);
            call(output.as_mut_ptr());
        }
        drop(allocation);
        output
    }
}
impl Drop for Module {
    fn drop(&mut self) {
        // SAFETY: All calls and reads have completed, and this object owns the LoadLibrary reference
        assert_ne!(unsafe { FreeLibrary(self.handle) }, 0);
    }
}

fn probe(gate: u64, address: u64, initial: &[u64; 15]) -> Vec<u8> {
    let mut a = CodeAssembler::new(64).expect("assembler");
    for r in [rbx, rbp, rsi, rdi, r12, r13, r14, r15] {
        a.push(r).expect("save caller");
    }
    a.sub(rsp, 24).expect("aligned metadata");
    a.mov(qword_ptr(rsp), rcx).expect("Windows output argument");
    a.mov(rax, gate).expect("gate pointer");
    a.mov(qword_ptr(rsp + 8), rax).expect("store gate");
    a.mov(rax, 0x5a5a5a5a5a5a5a5au64).expect("canary");
    a.sub(rsp, 512).expect("reserve canary region");
    for offset in (0..512).step_by(8) {
        a.mov(qword_ptr(rsp + offset), rax).expect("fill");
    }
    a.add(rsp, 512).expect("restore probe stack");
    a.mov(rax, qword_ptr(rsp)).expect("output");
    a.mov(qword_ptr(rax + 128), rsp).expect("pre-call RSP");
    a.mov(rax, 0x202u64).expect("flags");
    a.push(rax).expect("flags");
    a.popfq().expect("flags");
    let regs = [
        rax, rcx, rdx, rbx, rbp, rsi, rdi, r8, r9, r10, r11, r12, r13, r14, r15,
    ];
    for (i, r) in regs.into_iter().enumerate() {
        a.mov(r, initial[i]).expect("guest sentinel");
    }
    a.call(qword_ptr(rsp + 8)).expect("raw gate call");
    a.pushfq().expect("observe flags");
    for r in regs {
        a.push(r).expect("observe GPR");
    }
    a.mov(rdx, qword_ptr(rsp + 128)).expect("output pointer");
    for i in 0..15 {
        a.mov(rax, qword_ptr(rsp + (14 - i) * 8)).expect("snapshot");
        a.mov(qword_ptr(rdx + i * 8), rax).expect("output");
    }
    a.mov(rax, qword_ptr(rsp + 120)).expect("saved flags");
    a.mov(qword_ptr(rdx + 120), rax).expect("output flags");
    a.lea(rax, qword_ptr(rsp + 128)).expect("post-call RSP");
    a.mov(qword_ptr(rdx + 136), rax).expect("output RSP");
    a.mov(rax, qword_ptr(rsp - 280))
        .expect("below deepest gate write");
    a.mov(qword_ptr(rdx + 144), rax).expect("output canary");
    a.lea(rsp, qword_ptr(rsp + 152))
        .expect("drop snapshot and metadata");
    for r in [r15, r14, r13, r12, rdi, rsi, rbp, rbx] {
        a.pop(r).expect("restore caller");
    }
    a.ret().expect("return");
    a.assemble(address).expect("assemble probe")
}
